name: rolo
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auth_buttons: ^1.0.1
  image_picker: ^0.7.4
  toast: ^0.1.5
  flutter_tindercard: ^0.2.0
  font_awesome_flutter: ^9.0.0
  on_boarding_ui: ^0.0.4
  share: ^2.0.1
  video_player: ^2.1.1
  chewie: ^1.0.0
  rflutter_alert: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/me.jpg
   - assets/sea.jpeg
   - assets/ocean.jpeg
   - assets/shore.jpeg
   - assets/new.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
